name: go

concurrency:
  group: ${{ github.workflow }}/${{ github.ref_name }}

on:
  push:
    paths:
      - '**.go'
      - '**.sql'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - '**.sql'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: make test
